### ISSUE TITLE
Error while installing from source

### ISSUE THREAD

**Issue by marcelo321** [Edu4rdSHL/findomain#83] opened 2020-03-27 02:54 UTC
I'm facing an issue while trying to install findomain from source. Any idea why this is happening or how to fix this?

```
error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-protocol-0.5.0/src/message/backend.rs:75:1
   |
75 | #[non_exhaustive]
   | ^^^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/44109

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `postgres-protocol`.
warning: build failed, waiting for other jobs to finish...
error: build failed```

**Comment by Edu4rdSHL** [comment] 2020-03-27 03:03
Duplicate of #70

**Closed by Edu4rdSHL** 2020-03-27 03:03 UTC
