### ISSUE TITLE
Add the possibility to use DoT

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#37] opened 2019-11-08 03:26 UTC
I prefer the easy way like CURL
Example:
`curl --doh-url https://dns.nextdns.io/[Your_ID] domain.url.com/download.example`
With DNS over TLS, searching for subdomains is safer.

**Comment by Edu4rdSHL** [comment] 2019-11-08 03:37
Hello. By the way do you want DoH (DNS over HTTPS) or DNS over TLS? The issue title points to DoH, if it's what you're requiring then it will not be implemented, otherwise I will work on it.

**Comment by ZeroDot1** [comment] 2019-11-08 03:42
You can also implement DoT instead of DoH, I can use both depending on what is available.
DoH or DoT would make searching for subdomains more secure.

**Comment by Edu4rdSHL** [comment] 2019-11-08 03:45
DNS-over-HTTPS is an ugly hack, to try to camouflage DNS queries as web queries, and get them past redirecting proxies (such as many telcos use) and protocol filters and so forth. That said, like NAT, it's an ugly hack that will probably have legs, that's why I will not work on it.

DoT is an actual IETF standard with a lot of interoperability work behind it. As a consequence of that, it's the most widely supported in software and I will work on it.

**Comment by ZeroDot1** [comment] 2019-11-08 03:50
OK, thanks for working on that.
I really appreciate it.

**Comment by ZeroDot1** [comment] 2019-11-08 04:13
I recommend to provide a way to configure the DoT settings in the configuration file, so that you don't have to enter everything manually every time you need to use it.

https://developers.cloudflare.com/1.1.1.1/dns-over-tls/

**Comment by Edu4rdSHL** [comment] 2019-11-08 04:15
It will be enabled using a flag like `--enable-dot`, currently Findomain doesn't have a configuration file.

**Comment by Edu4rdSHL** [comment] 2019-11-09 04:54
@ZeroDot1 please can you test the 0.9.0-beta1 release? https://github.com/Edu4rdSHL/findomain/releases/tag/0.9.0-beta1

Please test all possible scenarios if possible.

**Comment by ZeroDot1** [comment] 2019-11-09 05:26
Hi @Edu4rdSHL,
Thank you for implementing the feature.

OK, I've updated via `yay -S findomain-git` to the latest version.

After I started my standattest for subdomains with the additional flag `--enable-dot` there was only one error and the program was stopped.
I looked into the source code to see if I use it correctly. 

`findomain -f "URLsToScan.txt" -i --enable-dot -u 'DONE.txt'`

```bash
error: Found argument '--enable-dot' which wasn't expected, or isn't valid in this context

USAGE:
    findomain --file <file> --resolved

For more information try --help
```
```bash
error: Found argument '--enable-dot' which wasn't expected, or isn't valid in this context

USAGE:
    findomain --file <file> --ip

For more information try --help

```
```bash
findomain -h
findomain 0.8.0
Eduard Tolosa <edu4rdshl@protonmail.com>
The fastest and cross-platform subdomain enumerator, don't waste your time.

USAGE:
    findomain [FLAGS] [OPTIONS]

FLAGS:
    -h, --help               Prints help information
    -i, --ip                 Show/write the ip address of resolved subdomains.
    -m, --monitoring-flag    Activate Findomain monitoring mode.
    -o, --output             Write to an output file. The name of the output file will be the target string with TXT
                             format.
        --query-database     Query the findomain database to search subdomains that have already been discovered.
    -q, --quiet              Remove informative messages but show fatal errors or subdomains not found message.
    -r, --resolved           Show/write only resolved subdomains.
    -V, --version            Prints version information

OPTIONS:
    -f, --file <file>                                 Use a list of subdomains writen in a file as input.
        --import-subdomains <import-subdomains>...
            Import subdomains from one or multiple files. Subdomains need to be one per line in the file to import.

        --postgres-database <postgres-database>       Postgresql database.
        --postgres-host <postgres-host>               Postgresql host.
        --postgres-password <postgres-password>       Postgresql password.
        --postgres-port <postgres-port>               Postgresql port.
        --postgres-user <postgres-user>               Postgresql username.
    -t, --target <target>                             Target host.
    -u, --unique-output <unique-output>
            Write all the results for a target or a list of targets to a specified filename.

```

**Comment by Edu4rdSHL** [comment] 2019-11-09 13:23
Hi @ZeroDot1, as you can see you're still using the current stable release (0.8.0) that doesn't have that features. You need to use the [develop branch](https://github.com/Edu4rdSHL/findomain/tree/develop) for testing purposes if you're going to use git or use the assets that are in the github releases section.

**Comment by Edu4rdSHL** [comment] 2019-11-09 16:05
According to the talk in Twitter, at the moment I can't implement DoT for API querys but only for resolvers while discovering IP addresses. I though DoT for a tool as Findomain isn't strictly necessary because you can configure it in the system configuration.

Is the current implementation fine? Is yes, I will mark is issue as solved, otherwise then I will revert the current implementation and mark it issue as wontfix.

**Comment by ZeroDot1** [comment] 2019-11-09 16:08
The current implementation is fine.
I still have to test if everything works as it should.

**Comment by ZeroDot1** [comment] 2019-11-09 20:13
OK, I have completed my tests when I use the switch `--enable-dot` Findoman needs very long for DNS resolving.
`findomain -f "URLsToScan.txt" -i --enable-dot -u 'DONE.txt'`
The following errors occurred:
```
A error has occurred while querying the Crtsh database. Error: database error. Trying the API method...
A timeout error has occurred while processing the request in the Sublist3r API. Error description: timed out
```
I have let findomain run for 4 hours and only 3 of 480 domains have been processed ...

**Comment by Edu4rdSHL** [comment] 2019-11-09 20:49
> OK, I have completed my tests when I use the switch --enable-dot Findoman needs very long for DNS resolving.

That's the price for using that feature in the client side when it needs to perform a **LOT** of DNS queries. There aren't cache or similar, every query is a new one.

>  The following errors occurred:

Those are API errors and I can't do anything, these errors occurs most times when targets are too long and the host can't reply in the limit time (20 seconds). It doesn't make sense to increase the timeout too because when they doesn't reply in 20 seconds they will not reply in 30 seconds, one minute or more.

> I have let findomain run for 4 hours and only 3 of 480 domains have been processed ...

It depends on how large are the targets, if they have thousands of subdomains then it's expected because you need to query each subdomain and wait if it send a reply or not.

**Comment by ZeroDot1** [comment] 2019-11-09 21:17
OK, I recommend you to build a routine that will automatically change the DNS server after 1 second if the DNS server does not answer.
Every DNS request should start with the user defined DNS server first if a user defined DNS server is used.

**Comment by Edu4rdSHL** [comment] 2019-11-11 06:44
Hi @ZeroDot1,

I just have finished an asynchronous subdomain ip's resolution that will reduce the time drastically. See https://github.com/Edu4rdSHL/findomain/commit/604d0a1ffb40731aa3df01fd5540649bce777012

**Benchmark results:**
Old implementation:
```
└─ ▶ time findomain -t kali.org -r
...
real	1m56.921s
```
New implementation:
```
─ ▶ time ./target/release/findomain -t kali.org -r
...
real	0m11.831s
```
As you can see, the time has been reduced from 117 seconds to 12 seconds for a target that have 87 subdomains and 75 are resolvable.

**Comment by ZeroDot1** [comment] 2019-11-11 06:47
Hi, @Edu4rdSHL,
That looks very good, I'll test it as soon as I have time.
Thanks, and keep up the good work!

**Comment by Edu4rdSHL** [comment] 2019-11-11 07:24
Another test suggest:

```
A total of 502 subdomains were found for ==>  asus.com 👽

Good luck Hax0r 💀!

real	1m11.712s
```
\> 500 subdomains in 1 minute + 11 seconds isn't bad. For your information, you can manage the number of threads with the `--threads` parameter. By default Findomain uses 50 threads that's safe and low in resources. If you set an arbitrary number like 99999999 in the threads number it will be set to 500 by safety. https://github.com/Edu4rdSHL/findomain/commit/efd51c4e7aacf350abe4e5235737e05ac7d14612

@sumgr0 please can you also test it feature? Specially the writing to file process but not limited to.

**Comment by ZeroDot1** [comment] 2019-11-11 15:56
Hi @Edu4rdSHL,

OK, I tested it, and after the second url, there was a error:

`findomain -f "URLsToScan.txt" -r --enable-dot -u 'DONE.txt'`

```bash
Target ==> 1stpool.org

Searching in the CertSpotter API... 🔍
Searching in the Spyse API... 🔍
Searching in the Threatcrowd API... 🔍
Searching in the Bufferover API... 🔍
Searching in the AnubisDB API... 🔍
Searching in the Virustotal API... 🔍
Searching in the Crtsh database API... 🔍
Searching in the Sublist3r API... 🔍
Searching in the Facebook API... 🔍

Performing asynchronous resolution for 10 subdomains with 50 threads, it will take a while. 🧐

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadPoolBuildError { kind: GlobalPoolAlreadyInitialized }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

**Comment by Edu4rdSHL** [comment] 2019-11-11 16:22
I can not reproduce the issue:

```
└─ ▶ ./target/release/findomain -t 1stpool.org -r --enable-dot -u DONE.txt

Target ==> 1stpool.org

Searching in the CertSpotter API... 🔍
Searching in the Crtsh database API... 🔍
Searching in the Virustotal API... 🔍
Searching in the Sublist3r API... 🔍
Searching in the Bufferover API... 🔍
Searching in the Facebook API... 🔍
Searching in the Threatcrowd API... 🔍
Searching in the Spyse API... 🔍
Searching in the AnubisDB API... 🔍
❌ An error occurred while parsing the JSON obtained from the Facebook API. Error description: JSON error.

Performing asynchronous subdomains resolution for 10 subdomains with 50 threads, it will take a while. 🧐

info.1stpool.org
etc.1stpool.org
www.1stpool.org
vrm.1stpool.org
stats.1stpool.org
nrg.1stpool.org
etho.1stpool.org

A total of 7 subdomains were found for ==>  1stpool.org 👽

Good luck Hax0r 💀!

>> 📁 Subdomains for 1stpool.org were saved in: ./DONE.txt 😀
```

**Comment by ZeroDot1** [comment] 2019-11-11 18:26
I could reproduce the error. it is possible that the error happens because I have very slow internet here in Germany.

**Comment by Edu4rdSHL** [comment] 2019-11-11 18:28
Will be good if you can reproduce the error and give me details.

**Comment by ZeroDot1** [comment] 2019-11-11 18:38
I used the same settings as above.
And a list to test with over 600URLs.
As system I use here: 
Kernel: 5.3.8-arch1-1 x86_64
Desktop: Cinnamon 4.2.4 
Distro: Arch Linux
Shell: bash 5.0.11

**Comment by Edu4rdSHL** [comment] 2019-11-11 22:51
@ZeroDot1 fixed.

**Closed** 2019-11-13 02:13 UTC
Labels: request-for-enhancement
