### ISSUE TITLE
Findomain 3.0 broke the output format

### ISSUE THREAD

**Issue by sumgr0** [Edu4rdSHL/findomain#24] opened 2019-09-26 04:33 UTC
I've just updated findomain to 3.0 and noticed the output txt file is no more one subdomain per line, the output is continuous now.

This is happening when using file as input, single target domain and for both output methods, -o and -u.

Look like the new line code is missing.

**Comment by Edu4rdSHL** [comment] 2019-09-26 04:35
Yeah, it was fixed in https://github.com/Edu4rdSHL/findomain/commit/2158a282cf99eccde0e863339f2dea86300b7188 and new assets has been uploaded. Please download again the binary or pull the repository.

**Closed by Edu4rdSHL** 2019-09-26 04:35 UTC

**Comment by sumgr0** [comment] 2019-09-26 04:37
Great, let me do a refresh and try again.

Thanks for the quick resolve

**Comment by Edu4rdSHL** [comment] 2019-09-26 04:39
No worries, please let me know if the issue is fixed and feel free to open others if you found new bugs.

**Comment by sumgr0** [comment] 2019-09-26 04:40
BTW using the -u option still results in continuous output, is it intended? Trying the single domain output for now.

**Comment by Edu4rdSHL** [comment] 2019-09-27 00:45
@sumgr0 I have received the following message but I haven't idea why it doesn't appear here. The problem has been fixed in https://github.com/Edu4rdSHL/findomain/commit/75146c3e19866dfaf432577943e9e42b067576d2.

![image](https://user-images.githubusercontent.com/32582878/65733855-011e7400-e096-11e9-90a7-e8e9fce93ab9.png)

**Comment by sumgr0** [comment] 2019-09-27 00:56
I confirm, this has been solved and working as expected after updating post your message.
