### ISSUE TITLE
Add a --max-time option

### ISSUE THREAD

**Issue by ZeroDot1** [Edu4rdSHL/findomain#95] opened 2020-04-21 18:52 UTC
This option is very helpful in very slow networks.
The --max-time option should allow you to limit the time for a scan, (for one domain).

For example, if a scan for one domain takes 15 minutes to complete, a multi-domain scan is very time consuming, especially on slow networks.
However, if you have an option --max-time which allows you to limit a scan to a specific time, you can save a lot of time.
I think this is very helpful for some users. 

Example: 
```
findomain -c '/config.toml' --verbose --resolvers '/resolvers.txt' --max-time 15 -t google.com
# A domain will only be scanned for 15 seconds, then you can continue with the next domain.
```

**Comment by Edu4rdSHL** [comment] 2020-04-21 19:14
I have never saw that an scan takes more than 15 minutes (with scan I mean the time used to discover the subdomains, not the resolving process and more). Discovering process just take a few seconds. I'm not sure what you are referring to, can you explain a bit more?

**Comment by ZeroDot1** [comment] 2020-04-21 19:42
I mean the subdomain discovery process I have seen it take sometimes 10 minutes if there are many subdomains with a --max-time option you could limit the time of discovery.

**Comment by Edu4rdSHL** [comment] 2020-04-26 20:25
When you say "the subdomain discovery process", did you mean the API searching process?

**Comment by ZeroDot1** [comment] 2020-04-29 10:08
That's exactly what I meant.

**Comment by Edu4rdSHL** [comment] 2020-04-29 13:26
It's most likely because the archive.org scrapping. I'm not going to implement that sincerely because:

1) I can't reproduce the issue, the max time I have seen is ~5 minutes.
2) Monitoring every thread in a multi thread process is very hard.
3) You have an option to exclude the archiveorg source.

**Closed by Edu4rdSHL** 2020-04-29 13:26 UTC
Labels: discussing, waiting-info
